export const FETCH_NODES = 'FETCH_NODES';
export const FETCH_NAMESPACES = 'FETCH_NAMESPACES';
export const FETCH_NAMESPACE_PODS = 'FETCH_NAMESPACE_PODS';
export const FETCH_NAMESPACE_SERVICES = 'FETCH_NAMESPACE_SERVICES';
export const FETCH_NAMESPACE_REPLICATIONCONTROLLERS = 'FETCH_NAMESPACE_REPLICATIONCONTROLLERS';
